# Generated by Django 4.1.1 on 2022-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_alter_custom_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_users',
            name='username',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
