# Generated by Django 4.1.1 on 2022-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_alter_custom_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_users',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
