# Generated by Django 4.1.1 on 2022-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0006_alter_custom_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_users',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
