# Generated by Django 4.1.1 on 2022-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0008_custom_users_company_name_custom_users_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_users',
            name='is_alumni',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='custom_users',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='custom_users',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='my_picture'),
        ),
    ]
