# Generated by Django 4.1.1 on 2022-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0010_custom_users_company_name_custom_users_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='my_picture')),
                ('name', models.CharField(max_length=255)),
                ('achievements', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
